---
:development: &defaults
  :adapter: mysql
  :database: irclogger
  :username: fake_user
  :password: fake_password
  :host: localhost

:test:
  <<: *defaults
  :database: irclogger_test

:production:
  <<: *defaults
  :database: irclogger

